version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: mysql-petshop
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: petshop
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d # caso queira scripts de criação

  app:
    build: /petshop
    container_name: backend-petshop
    ports:
      - "80:80"
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      DB_NAME: petshop
      DB_USER: root
      DB_PASSWORD: root
    restart: always
    command: npm start

volumes:
  db_data:
