version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: mysql-petshop
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: petshop
      MYSQL_USER: dev
      MYSQL_PASSWORD: uscs
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d # caso queira scripts de criação

  app:
    build: .
    container_name: petshop-backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app
    env_file:
      - .env
    restart: always
    command: npm start

volumes:
  db_data:
